name: Benchmark on label 'do-benchmark'

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

permissions:
  issues: write
  pull-requests: write

jobs:
  bench-coke:
    name: Coke Benchmark
    runs-on: ubuntu-24.04
    if: (contains('["issues", "pull_request"]', github.event_name) && github.event.label.name == 'do-benchmark' && github.actor == 'kedixa')
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build and benchmark
      run: |
        bazel build //benchmark:all_benchmarks

        (echo "# Benchmark"
        echo "The benchmark runs on Github Actions."
        echo ""

        echo "## Environment"
        echo "<details><summary>Details</summary> <p>"
        echo ""
        echo "\`\`\`"
        lscpu
        echo ""
        lsmem
        echo "\`\`\`"
        echo ""
        echo "</p> </details>"
        echo ""

        echo "## Go"
        echo "Bench command \`bench_go --concurrency 64 --compute 8 --max-secs 60 --total 200000 --times 5 -y\`"
        echo ""
        echo "<details><summary>Details</summary> <p>"
        echo ""
        ./bazel-bin/benchmark/bench_go --concurrency 64 --compute 8 --max-secs 60 --total 200000 --times 5 -y
        echo ""
        echo "</p> </details>"
        echo ""

        echo "## Timer"
        echo "Bench command \`bench_timer --concurrency 4096 --handler 12 --poller 6 --compute 8 --max-secs 60 --total 200000 --times 5 -y\`"
        echo ""
        echo "<details><summary>Details</summary> <p>"
        echo ""
        ./bazel-bin/benchmark/bench_timer --concurrency 4096 --handler 12 --poller 6 --compute 8 --max-secs 60 --total 200000 --times 5 -y
        echo ""
        echo "</p> </details>"
        echo ""

        echo "## Dag"
        echo "Bench command \`bench_graph --num-nodes 128 --total 500 --group-size 10 --task-per-node 3 --max-secs 60 --times 5 --handler 12 --poller 6 -y\`"
        echo ""
        echo "<details><summary>Details</summary> <p>"
        echo ""
        ./bazel-bin/benchmark/bench_graph --num-nodes 128 --total 500 --group-size 10 --task-per-node 3 --max-secs 60 --times 5 --handler 12 --poller 6 -y
        echo ""
        echo "</p> </details>"
        echo ""

        echo "## Exception"
        echo "Bench command \`bench_exception --concurrency 4096 --total 200000 --max-secs 60 --times 5 --handler 12 --poller 6 -y\`"
        echo ""
        echo "<details><summary>Details</summary> <p>"
        echo ""
        ./bazel-bin/benchmark/bench_exception --concurrency 4096 --total 200000 --max-secs 60 --times 5 --handler 12 --poller 6 -y
        echo ""
        echo "</p> </details>"
        echo ""

        echo "## Queue"
        echo "Bench command \`bench_queue --concurrency 10 --total 1000000 --max-secs 60 --times 5 --que-size 1000 --batch-size 10 --handler 12 --poller 6 -y\`"
        echo ""
        echo "<details><summary>Details</summary> <p>"
        echo ""
        ./bazel-bin/benchmark/bench_queue --concurrency 10 --total 1000000 --max-secs 60 --times 5 --que-size 1000 --batch-size 10 --handler 12 --poller 6 -y
        echo ""
        echo "</p> </details>"
        echo ""

        echo "## Weighted NSPolicy"
        echo "Bench command \`./bazel-bin/benchmark/bench_weighted_policy --concurrency 1 --total 1000000 --times 5 -y\`"
        echo ""
        echo "<details><summary>Details</summary> <p>"
        echo ""
        ./bazel-bin/benchmark/bench_weighted_policy --concurrency 1 --total 1000000 --times 5 -y
        echo ""
        echo "</p> </details>"
        echo ""

        echo "## LruCache"
        echo "Bench command \`./bazel-bin/benchmark/bench_lru --total-ops 1000000 --max-threads 6 -y\`"
        echo ""
        echo "<details><summary>Details</summary> <p>"
        echo ""
        ./bazel-bin/benchmark/bench_lru --total-ops 1000000 --max-threads 6 -y
        echo ""
        echo "</p> </details>"
        echo ""

        ) > bench.md

    - name: Comment
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs/promises')
          const data = await fs.readFile('./bench.md', 'utf-8')

          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            repo: context.repo.repo,
            owner: context.repo.owner,
            body: data
          });

          await github.rest.issues.removeLabel({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            name: 'do-benchmark',
          });
