on:
  pull_request:
    branches:
    - master
  workflow_dispatch:

env:
  wf_tag: v0.11.3

jobs:
  build-centos-stream8:
    name: centos-stream8
    runs-on: ubuntu-22.04
    container:
      image: quay.io/centos/centos:stream8
    strategy:
      matrix:
        compiler_prepare: [
          "source scl_source enable gcc-toolset-12",
          "export CC=clang CXX=clang++"
        ]
    steps:
    - name: Prepare
      run: |
        dnf install -y gcc-toolset-12-gcc gcc-toolset-12-gcc-c++ \
          openssl openssl-devel \
          clang git cmake valgrind
        dnf --enablerepo=powertools install -y gtest-devel
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: sogou/workflow
        ref: ${{ env.wf_tag }}
        path: workflow
    - name: Build
      run: |
        ${{ matrix.compiler_prepare }}
        cmake -S workflow -B build.workflow -D CMAKE_CXX_STANDARD=20
        make -C workflow -j 8
        cmake -S . -B build -D Workflow_DIR=workflow -D COKE_ENABLE_TEST=1 -D COKE_ENABLE_EXAMPLE=1 -D COKE_ENABLE_BENCHMARK=1
        make -C build -j 8 all test
